### ISSUE TITLE
Makes jest work with chalk 5

### ISSUE THREAD

**Issue by ArondilBe** [ArondilBe/monorepo-package-generator#50]
### Task description
Modify jest or other config to make jest work with chalk

**Comment by webdiscus** [comment]
The chalk 5 the supports only ESM, but Jest requires CommonJS.

You can switch to the [ansis](https://github.com/webdiscus/ansis) (alternative to chalk), that is fully compatible with chalk syntax.
The `ansis` supports both the `ESM` and `CommonJS`.

The migration is very simple:
```diff
// using ESM
- import chalk from 'chalk';
+ import chalk from 'ansis';

// using CommonJS
- const chalk = require('chalk');
+ const chalk = require('ansis');

chalk.green.bold('Done!'); // <- the Chalk like syntax works fine with Ansis
```
